// Generated by CoffeeScript 1.6.3
(function() {
  this.Map = cc.Node.extend({
    init: function() {
      var column, desc, item, row, tile, tileId, tileKlass, type, x, y, _i, _j, _k, _len, _ref;
      this._super();
      this.numCols = 16;
      this.numRows = 11;
      this.itemsByTag = {};
      desc = this.description();
      this.tiles = [];
      for (x = _i = 0; _i < 16; x = ++_i) {
        column = [];
        row = desc.cols[x];
        for (y = _j = 0; _j < 11; y = ++_j) {
          tileId = row[y];
          tileKlass = this.idToTile(tileId);
          tile = tileKlass.create(x, y);
          this.addChild(tile);
          column.push(tile);
        }
        this.tiles.push(column);
      }
      _ref = desc.items;
      for (_k = 0, _len = _ref.length; _k < _len; _k++) {
        item = _ref[_k];
        x = item.x;
        y = item.y;
        type = item.type;
        tile = this.addItem(x, y, type, item);
      }
      this.isDemo = desc.isDemo;
      this.inventory = desc.inventory;
      this.nextLevel = desc.nextLevel;
      this.playerStart = desc.playerStart;
      return true;
    },
    playerCanMoveForward: function(player) {
      var newPosition, nextTile;
      newPosition = player.getNextTilePosition();
      nextTile = this.tiles[newPosition.x][newPosition.y];
      return nextTile.canEnter();
    },
    playerMoveCompleted: function(player) {
      var currentPosition, currentTile;
      currentPosition = player.getTilePosition();
      currentTile = this.tiles[currentPosition.x][currentPosition.y];
      return currentTile.playerEntered(player);
    },
    addItem: function(x, y, type, item) {
      var tag;
      item = this.tiles[x][y].addItem(type, item, this);
      if (item) {
        tag = item.getTag();
        if (tag) {
          this.itemsByTag[tag] = item;
        }
      }
      return item;
    },
    getItemByTag: function(tag) {
      return this.itemsByTag[tag];
    },
    idToTile: function(id) {
      switch (id) {
        case Map.ids.empty:
          return EmptyTile;
        case Map.ids.wall:
          return WallTile;
      }
    },
    isDemoMode: function() {
      return this.isDemo;
    },
    getNextLevel: function() {
      return this.nextLevel;
    },
    getInventory: function() {
      return this.inventory;
    },
    getPlayerStart: function() {
      return this.playerStart;
    },
    isBorder: function(x, y) {
      return x === 0 || x === (this.numCols - 1) || y === 0 || y === (this.numRows - 1);
    },
    emptyMap: function() {
      var col, cols, tileId, x, y, _i, _j, _ref, _ref1;
      cols = [];
      for (x = _i = 0, _ref = this.numCols; 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
        col = [];
        for (y = _j = 0, _ref1 = this.numRows; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          tileId = this.isBorder(x, y) ? Map.ids.wall : Map.ids.empty;
          col.push(tileId);
        }
        cols.push(col);
      }
      return cols;
    }
  });

  this.Map.ids = {
    empty: 0,
    wall: 1
  };

  this.Map.create = function(mapJson) {
    var map;
    map = new Map();
    map.init();
    return map;
  };

}).call(this);
