// Generated by CoffeeScript 1.6.3
(function() {
  this.MapSix = Map.extend({
    description: function() {
      var base, level, x, y, _i, _j;
      base = this.emptyMap();
      for (y = _i = 4; _i <= 6; y = ++_i) {
        for (x = _j = 1; _j <= 14; x = ++_j) {
          base[x][y] = Map.ids.wall;
        }
      }
      level = {
        cols: base,
        items: [
          {
            x: 14,
            y: 8,
            type: PortalA,
            destinationX: 1,
            destinationY: 2
          }, {
            x: 14,
            y: 2,
            type: Goal
          }
        ],
        inventory: [
          {
            type: PortalB,
            destinationX: 14,
            destinationY: 8
          }
        ],
        playerStart: {
          x: 1,
          y: 8,
          rotation: 90
        },
        nextLevel: MapSeven
      };
      return level;
    }
  });

  MapSix.create = function() {
    var map;
    map = new MapSix();
    map.init();
    return map;
  };

}).call(this);
