// Generated by CoffeeScript 1.6.3
(function() {
  this.MapDemo = Map.extend({
    description: function() {
      var level;
      level = {
        cols: this.emptyMap(),
        items: [
          {
            x: 2,
            y: 2,
            type: ChangeDirection,
            newDirection: 0
          }, {
            x: 2,
            y: 8,
            type: ChangeDirection,
            newDirection: 90
          }, {
            x: 13,
            y: 8,
            type: ChangeDirection,
            newDirection: 180
          }, {
            x: 13,
            y: 2,
            type: ChangeDirection,
            newDirection: 270
          }
        ],
        inventory: [],
        playerStart: {
          x: 2,
          y: 3,
          rotation: 0
        },
        nextLevel: MapOne,
        isDemo: true
      };
      return level;
    }
  });

  MapDemo.create = function() {
    var map;
    map = new MapDemo();
    map.init();
    return map;
  };

}).call(this);
