// Generated by CoffeeScript 1.6.3
(function() {
  this.sprite_sheet_plist = "sprite_sheet.plist";

  this.sprite_sheet_png = "sprite_sheet.png";

  this.empty = "empty.png";

  this.wall = "wall.png";

  this.player = "player.png";

  this.change_direction = "change_direction.png";

  this.g_resources = [
    {
      src: empty
    }, {
      src: wall
    }, {
      src: player
    }, {
      src: sprite_sheet_plist
    }, {
      src: sprite_sheet_png
    }, {
      src: change_direction
    }
  ];

}).call(this);
