// Generated by CoffeeScript 1.6.3
(function() {
  this.GameLayer = cc.Layer.extend({
    init: function() {
      this._super();
      this.setTouchEnabled(true);
      return true;
    },
    menuCloseCallback: function(sender) {
      return true;
    },
    onTouchesBegan: function(touches, events) {
      return true;
    },
    onTouchesMoved: function(touches, event) {
      return true;
    },
    onTouchesEnded: function(touches, event) {
      return true;
    },
    onTouchesCancelled: function(touches, event) {
      return true;
    }
  });

  this.TenSecondsScene = cc.Scene.extend({
    onEnter: function() {
      var layer;
      this._super();
      layer = new GameLayer();
      layer.init();
      return this.addChild(layer);
    }
  });

}).call(this);
