// Generated by CoffeeScript 1.6.3
(function() {
  this.Tile = cc.Sprite.extend({
    init: function(filename, x, y) {
      this._super();
      this.initWithFile(filename);
      this.setPosition(cc.p(x * 64, y * 64));
      this.setAnchorPoint(cc.p(0, 0));
      this.position = cc.p(x, y);
      return this.items = [];
    },
    addItem: function(item, description, map) {
      var newItem;
      newItem = item.create(description, map, this);
      this.addChild(newItem);
      this.items.push(newItem);
      if (this.currentPlayer) {
        this.itemCompleted(this.currentPlayer);
      }
      return newItem;
    },
    getPosition: function() {
      return this.position;
    },
    playerEntered: function(player) {
      this.currentPlayer = player;
      this.currentItemIndex = 0;
      return this.itemCompleted();
    },
    reprocessItems: function() {
      if (this.currentPlayer) {
        this.currentItemIndex = 0;
        return this.itemCompleted();
      }
    },
    itemCompleted: function() {
      var currentItem, player;
      if (this.currentItemIndex < this.items.length) {
        currentItem = this.items[this.currentItem];
        this.handleCurrentItem(this.currentPlayer);
        return this.currentItemIndex++;
      } else {
        if (this.currentPlayer.canMoveForward()) {
          player = this.currentPlayer;
          this.currentPlayer = void 0;
          return player.moveForward();
        }
      }
    },
    handleCurrentItem: function(player) {
      return this.items[this.currentItemIndex].interact(player, this);
    },
    canEnter: function() {
      return true;
    }
  });

  this.EmptyTile = Tile.extend({
    init: function(x, y) {
      return this._super(empty, x, y);
    }
  });

  EmptyTile.create = function(x, y) {
    var tile;
    tile = new EmptyTile();
    tile.init(x, y);
    return tile;
  };

  this.WallTile = Tile.extend({
    init: function(x, y) {
      return this._super(wall, x, y);
    },
    addItem: function(item, description, map) {
      return false;
    },
    canEnter: function() {
      return false;
    }
  });

  WallTile.create = function(x, y) {
    var tile;
    tile = new WallTile();
    tile.init(x, y);
    return tile;
  };

}).call(this);
